# Generated by Django 5.2.17 on 2026-08-18 16:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SapIntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SAP_URL', models.CharField(help_text='SAP OData service URL', max_length=500, validators=[django.core.validators.URLValidator()])),
                ('SAP_USERNAME', models.CharField(blank=True, max_length=255)),
                ('SAP_PASSWORD', models.CharField(blank=True, max_length=500)),
                ('SAP_CLIENT', models.CharField(default='100', max_length=10)),
                ('SAP_LANGUAGE', models.CharField(default='EN', max_length=2)),
                ('AUTO_SYNC', models.BooleanField(default=True)),
                ('SYNC_INTERVAL', models.IntegerField(default=3600, help_text='Sync interval in seconds')),
                ('EMPLOYEE_ENTITY', models.CharField(default='Employees', help_text='SAP entity name for employees', max_length=255)),
                ('IS_ACTIVE', models.BooleanField(default=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SAP Integration Configuration',
                'verbose_name_plural': 'SAP Integration Configurations',
            },
        ),
        migrations.CreateModel(
            name='SapEmployeeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_employee_id', models.CharField(max_length=255, unique=True)),
                ('sap_personnel_number', models.CharField(blank=True, max_length=255)),
                ('is_synced', models.BooleanField(default=False)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('solich_employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sap_mapping', to='employee.employee')),
            ],
            options={
                'verbose_name': 'SAP Employee Mapping',
                'verbose_name_plural': 'SAP Employee Mappings',
            },
        ),
        migrations.CreateModel(
            name='SapPayrollMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solich_component', models.CharField(max_length=255)),
                ('sap_wage_type', models.CharField(max_length=10)),
                ('mapping_type', models.CharField(choices=[('basic_salary', 'Basic Salary'), ('allowance', 'Allowance'), ('deduction', 'Deduction'), ('tax', 'Tax'), ('contribution', 'Contribution')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SAP Payroll Mapping',
                'verbose_name_plural': 'SAP Payroll Mappings',
                'unique_together': {('solich_component', 'sap_wage_type')},
            },
        ),
        migrations.CreateModel(
            name='SapSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('employee', 'Employee'), ('payroll', 'Payroll'), ('attendance', 'Attendance'), ('leave', 'Leave'), ('recruitment', 'Recruitment'), ('general', 'General')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='pending', max_length=20)),
                ('records_synced', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='sap_integration.sapintegrationconfig')),
            ],
            options={
                'verbose_name': 'SAP Sync Log',
                'verbose_name_plural': 'SAP Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
